### ISSUE TITLE
How to setup intellisense and formatting? 

### ISSUE THREAD

**Issue by sebastianmacias** [Devpodio/theia-vue-extension#3]
I installed the extension and so far it highlights the .vue code however intellisense and formatting doesn't seem to be working. Are there any additional steps I might be missing or these features are not supported?

**Comment by uniibu** [comment]
Hi, sorry for the late response. I've updated the extension to `v0.2.0` which now uses all features of `vue-language-server` which includes:
- Syntax-highlighting
- Snippet
- Emmet
- Linting / Error Checking
- Formatting
- Auto Completion
- Debugging

However, this is only compatible with `@next` version of Theia packages eg. `@theia/core@next`, `@theia/editor@next` etc...

**Comment by sebastianmacias** [comment]
So far I have tested:

* Syntax-highlighting
* Formatting
* Auto Completion

Works great! Thank you for your work
